disp('Running MATLAB script file OODAfig14p4.m') ;
%
%    Makes Figure 14.4 of the OODA book,
%    HDLSS 3-d toy example
%
%    Copied from OODAbookChpMFigBViewGeomRep.m
%    in:        OODAbook\ChapterM
%

fighand = figure(1) ;
clf ;

titlefontsize = 10 ;
axlength = 1.5 ;
alpha = 3 * pi / 4 ;
beta1 = -pi/4 ;
vdat1d2 = 1.05 * [cos(beta1); sin(beta1)] ;
beta2 = pi / 3 ;
vdat2d2 = 0.95 * [cos(beta2); sin(beta2)] ;
vdat1d3 = 1.05 * [cos(beta1) * cos(alpha); cos(beta1) * sin(alpha); sin(beta1)] ;
vdat2d3 = 0.95 * [cos(beta2) * cos(alpha); cos(beta2) * sin(alpha); sin(beta2)] ;


subplot(2,2,1) ;
  plot3(axlength * [[-1;1],[0;0],[0;0]], ...
        axlength * [[0;0],[-1;1],[0;0]], ...
        axlength * [[0;0],[0;0],[-1;1]],'k-') ;
  axis square ;
  hold on ;
    plot3(vdat1d3(1),vdat1d3(2),vdat1d3(3),'ro') ;
    plot3(vdat2d3(1),vdat2d3(2),vdat2d3(3),'ro') ;
  hold off ;
  title('n = 2 Toy Data Points in 3-d','FontSize',titlefontsize) ;


subplot(2,2,2) ;
  plot3(axlength * [[-1;1],[0;0],[0;0]], ...
        axlength * [[0;0],[-1;1],[0;0]], ...
        axlength * [[0;0],[0;0],[-1;1]],'k-') ;
  axis square ;

  hold on ;
  
    ph = patch([cos(alpha); cos(alpha); -cos(alpha); -cos(alpha)]+0.001, ...
               [sin(alpha); sin(alpha); -sin(alpha); -sin(alpha)]+0.001, ...
               [-1; 1; 1; -1],'c') ;
%        set(ph,'FaceAlpha',0.5) ;

    plot3(vdat1d3(1),vdat1d3(2),vdat1d3(3),'ro') ;
    plot3(vdat2d3(1),vdat2d3(2),vdat2d3(3),'ro') ;
    plot3([vdat1d3(1);0],[vdat1d3(2);0],[vdat1d3(3);0],'r-') ;
    plot3([vdat2d3(1);0],[vdat2d3(2);0],[vdat2d3(3);0],'r-') ;
    plot3([vdat1d3(1);vdat2d3(1)],[vdat1d3(2);vdat2d3(2)], ...
          [vdat1d3(3);vdat2d3(3)],'r--') ;

  hold off ;
  title('Subspace (2-d) Generated by Data','FontSize',titlefontsize) ;


subplot(2,2,3) ;
  patch([1, 1, -1, -1, 1],[-1, 1, 1, -1, -1],'c') ;
  axis square ;
  axis([-axlength,axlength,-axlength,axlength]) ;

  hold on ;

    plot(axlength * [[-1;1],[0;0]], ...
         axlength * [[0;0],[-1;1]],'k-') ;

    plot(vdat1d2(1),vdat1d2(2),'ro') ;
    plot(vdat2d2(1),vdat2d2(2),'ro') ;
    plot([vdat1d2(1);0],[vdat1d2(2);0],'r-') ;
    plot([vdat2d2(1);0],[vdat2d2(2);0],'r-') ;
    plot([vdat1d2(1);vdat2d2(1)],[vdat1d2(2);vdat2d2(2)],'r--') ;

  hold off
  title('Rotation of Subspace to R^2','FontSize',titlefontsize) ;


  angle1 = atan2(vdat1d2(2),vdat1d2(1)) ;
  angle2 = atan2(vdat2d2(2),vdat2d2(1)) ;
  avangle = mean([angle1; angle2]) ;

  angrot = pi/4 - avangle ;
      %  angle to rotate, puts average angle at pi/4
  mrot = [[cos(angrot) -sin(angrot)]; [sin(angrot) cos(angrot)]] ;
      %  rotation matrix
  vdat1d2r = mrot * vdat1d2 ;
  vdat2d2r = mrot * vdat2d2 ;

subplot(2,2,4) ;
  plot(axlength * [[-1;1],[0;0]], ...
       axlength * [[0;0],[-1;1]],'k-') ;
  axis square ;
  axis([-axlength,axlength,-axlength,axlength]) ;

  hold on ;

    plot(vdat1d2r(1),vdat1d2r(2),'ro') ;
    plot(vdat2d2r(1),vdat2d2r(2),'ro') ;
    plot([vdat1d2r(1);0],[vdat1d2r(2);0],'r-') ;
    plot([vdat2d2r(1);0],[vdat2d2r(2);0],'r-') ;
    plot([vdat1d2r(1);vdat2d2r(1)],[vdat1d2r(2);vdat2d2r(2)],'r--') ;

    plot([0, 1],[1, 0],'ko') ;
    plot([0, 1],[1, 0],'k--') ;

  hold off
  title('Rotation Toward Unit Simplex','FontSize',titlefontsize) ;



%  Create png file
%
  orient portrait ;
  set(gcf,'PaperSize',[12.0, 10.0]) ; 
  set(gcf,'PaperPosition',[0.25, 0.25, 11.5, 9.5]) ; 
print('-dpng','OODAfig14p4.png') ;




